### ISSUE TITLE
www.sitename.com/responsivity

### ISSUE THREAD

**Issue by serdarkiziltepe** [bilaltas/responsivity#2]
Bu plugin'nin ekli olduğu sitelere Admin girişi olmadan müşterinin ve başkalarının mobil görünümler hakkında bilgi sahibi olabilmesi ve öneri sunması için "www.sitename.com/responsivity" şeklinde ekleme yapılıp direk cihazlar gösterilebilir.

**Comment by bilaltas** [comment]
https://github.com/bilaltas/responsivity/commit/f70d93695f82305e19483564f417083d4c079747 Burada yapıldı. Teşekkürler!
